Fix compilation errors and warnings and link failure
Compile-tested with commit 8ea3f0e (tag: 3.4.10)
from https://github.com/osmocom/libusrp

Fixes:
usrp_impl.cc:33:10: fatal error: usrp_standard.h: No such file or directory
usrp_impl.cc:49:63: error: expected '(' before 'malloc'
usrp_impl.cc:49:100: error: expected ')' before ';' token
usrp_impl.cc:72:39: error: invalid 'static_cast' from type 'rig_state*' to type 'usrp_priv_data*'
usrp_impl.cc:86:39: error: invalid 'static_cast' from type 'rig_state*' to type 'usrp_priv_data*'
usrp_impl.cc:104:39: error: invalid 'static_cast' from type 'rig_state*' to type 'usrp_priv_data*'
usrp_impl.cc:129:45: error: invalid 'static_cast' from type 'rig_state*' to type 'usrp_priv_data*'
usrp_impl.cc:151:45: error: invalid 'static_cast' from type 'rig_state*' to type 'usrp_priv_data*'
usrp_impl.cc:169:45: error: invalid 'static_cast' from type 'rig_state*' to type 'usrp_priv_data*'

usrp_impl.cc:114:37: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
usrp_impl.cc:139:38: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

/usr/bin/ld: ../src/.libs/libhamlib.so: undefined reference to `usrp_caps'