Attempt to quell Ubuntu CI error
Ubuntu CI is generating the following error:

E: Failed to fetch https://security.ubuntu.com/ubuntu/pool/main/u/util-linux/uuid-dev_2.39.3-9ubuntu6.2_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

This patch updates the repository cache.