Fix building Python bindings with SWIG 4.5
This change is compatible with SWIG 4.4.

Fixes:
 error: implicit declaration of function 'PyInt_FromLong'

SWIG commit that dropped the macros used for compatibility with Python 2:
 https://github.com/swig/swig/commit/79f7a2b7cb7ddc256eba09c8770133148025171d

Debian bug report:
 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1145352

(cherry picked from commit 40579c6213eee8e4d15b45d176deff3dcab79acd)