Append the missing information to build hamlib v4.3 for Android NDK
The following errors were fixed in this commit:
error: undefined symbol: rig_sprintf_vfo
error: undefined symbol: initrots2_radant
error: undefined symbol: ts890s_caps

(cherry picked from commit b5bd1f4036bb42ae8b5c05900f51cec60bf2502e)