Fix various unknown type compilation errors
When compiling Hamlib 4.7 on Alpine Linux, the build fails due to
several unknown type errors with the following message:

    error: unknown type name 'mode_t'; did you mean 'rmode_t'?

This commit adjusts the usage of mode_t to rmode_t to fix these
compilation errors. With these changes, Hamlib 4.7 builds on Alpine
Linux 3.21.6.

See PR #1642 for additional context.